image: alpine/edge
packages:
  - go
  - golangci-lint
sources:
  - https://github.com/go-ap/storage-sqlite
secrets:
  - 989da578-3fc1-4f6b-a116-d7c9f434b1f3
environment:
  GO111MODULE: 'on'
tasks:
  - fmt: |
      cd storage-sqlite
      test -z $(gofmt -l .)
  - tests: |
      cd storage-sqlite
      make test

  - coverage: |
      cd storage-sqlite
      git switch -C master origin/master
      make coverage
      go tool goveralls -flagname unit-tests -service=${CI_NAME} -coverprofile storage-sqlite.coverprofile -repotokenfile ~/.coveralls.tok
  - lint: |
      cd storage-sqlite
      golangci-lint run || true
