image: alpine/edge
packages:
  - go
sources:
  - https://github.com/go-ap/storage-sqlite
secrets:
  - 989da578-3fc1-4f6b-a116-d7c9f434b1f3
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd storage-sqlite
      make test

  - coverage: |
      cd storage-sqlite
      git switch -C master origin/master
      make coverage
      go run github.com/mattn/goveralls@latest -flagname unit-tests -service=${CI_NAME} -coverprofile storage-sqlite.coverprofile -repotokenfile ~/.coveralls.tok
